FillRaw solution
oseducation/programming-methodology-java pull request #10
Opened 2021-11-01 20:21 UTC by NikolozCh

This PR is solving the FillRaw problem. Includes .java and .md files

2021-11-08 18:04 UTC, iomodo requested changes
გადასარევია! ძალიან დიდი მადლობა @NikolozCh <3
ძალიან მიზერული შენიშვნები ჩამოვწერე ქვემოთ.

2021-11-08 18:04 UTC, iomodo commented on problem-set/FillRaw.md
> +
ენტერები

2021-11-08 18:04 UTC, iomodo commented on problem-set/FillRaw.md
> +### სიარულის პარალელურად, ბიპერების განთავსება ქუჩაზე
სხვაგანაც ყველგან, ბიპერის მაგივრად ბრილიანტი გამოვიყენოთ.

2021-11-08 18:04 UTC, iomodo commented on problem-set/FillRaw.md
> +    ![Karel in 1x10 World](https://i.imgur.com/RwZB99V.png)
სურათი ლოკალურად

2021-11-08 18:04 UTC, iomodo commented on problem-set/FillRaw.md
> +პირველ რიგში, მინდა მოგილოცოთ პროგრამის დასრულება წარმატებით დასრულება და იმპლემენტაცია, თუმცა არსებობს 2 დეტალი, რისი გათვალისწინებაც საკმაოდ მნიშვნელოვანია ამ ამოცანის გადაჭრისას
```suggestion
პირველ რიგში, მინდა მოგილოცოთ პროგრამის წარმატებით დასრულება და იმპლემენტაცია, თუმცა არსებობს 2 დეტალი, რისი გათვალისწინებაც საკმაოდ მნიშვნელოვანია ამ ამოცანის გადაჭრისას
```

2021-11-08 19:02 UTC, NikolozCh commented
ცვლილებები შეტანილია, @iomodo.

წესით ყველაფერი რიგზე უნდა იყოს.

2021-11-09 09:32 UTC, iomodo approved these changes
იდეალურია, მადლობა <3

2021-11-09 09:33 UTC, merged