30 sep 11:21
oseducation/programming-methodology-java pull request #47
Opened 2022-09-30 07:25 UTC by bmana21

Solved issue #29 (15. Avarage)

2022-10-02 17:11 UTC, iomodo requested changes

2022-10-02 17:11 UTC, iomodo commented on problem-set/Average.java
> +		double Avarage = (double) sum / 2; // Cast to double and divide by 2
ცვლადის სახელი პატარა სიმბოლოთი ჯობია იწყებოდას

2022-10-02 17:11 UTC, iomodo commented on problem-set/Average.md
> +2) გადავკასტოთ double_ში და გავყოთ ორზე.
კარგი იქნება არასწორი ამოხსნის მაგალითების ჩვენება და ახსნა რატომ არის ამოხსნა არასწორი. მაგალითად რატომ არ ვარგა
```java
double avarage = firstNumber + secondNumber / 2
```
და
```java
double avarage = (firstNumber + secondNumber) / 2
```

ან კიდე რატომ ვარგა
```java
double avarage = (firstNumber + secondNumber) / 2.0
```

2022-10-03 13:51 UTC, bmana21 commented
შეცდომები შევასწორე.

2022-10-04 21:24 UTC, iomodo commented
@bmana21 შესწორებების შეტანის მერე უბრალოდ შეგიძლია `Re-request review`-ს დააკლიკო

2022-10-04 21:54 UTC, iomodo requested changes

2022-10-04 21:54 UTC, iomodo commented on problem-set/Average.java
> + * File: FindRange.java
კომენტარები არ შეესაბამება ამოცანას

2022-10-04 21:54 UTC, iomodo commented on problem-set/Average.md
> +1) დავითვალოთ კონსოლიდან წაკითხული რიცხვების ჯამი. აუცილებელია ჯამი ცალკე ცვლადში დავთვალოთ, ან ორივე რიცხვის ჯამი ფრჩხილებში ჩავწეროთ და ისე გავყოთ ორზე, რადგან თუ დავწერდით double avarage = firstNu
ამოცანის სახელი(სათაური) და ტექსტი აკლია

2022-10-04 21:54 UTC, iomodo commented on problem-set/Average.md
> +3) სწორ პასუხს მივიღებდით, თუ 2_ს ფრჩხილებს გარეთ არ გავიტანდით და თითოეული რიცხვს ორზე გავყოფდით და ბოლოს შევკრებდით, მაგრამ ეს არ იქნებოდა ეფექტური, რადგან "/ 2.0"_ის დაწერა ორჯერ მოგვიწევდა.  avar
არ იკითხება ამოცანის ამოხსნა ამ ტექსტში. მსგავსი რამ აჯობებს:

განვიხილოთ ამოხსნა
```java
public class ConsoleProgrammSample extends ConsoleProgram {
 	private double getAvarage(int firstNumber, int secondNumber) {
 		return firstNumber + secondNumber / 2;
 	}

 	public void run() {
 		int firstNumber = readInt("Enter first number: ");
 		int secondNumber = readInt("Enter second number: ");
 		println(getAvarage(firstNumber, secondNumber));
 	}
 }
```
თითქოს სწორია, მუშაობს კიდეც რაღაც შემთხვევებისთვის მაგალითად როცა .... თუმცა ყველა შემთხვევაში არ იმუშავებს იმიტომ რომ ....

ახლა განვიხილოთ ამოხსნა

``` java
....
return (firstNumber + secondNumber) / 2;
....
```
თითქოს სწორია, მუშაობს კიდეც რაღაც შემთხვევებისთვის მაგალითად როცა .... თუმცა ყველა შემთხვევაში არ იმუშავებს იმიტომ რომ ....

შესაბამისად სწორი ამოხსნა იქნება
```java
...
int sum = firstNumber + secondNumber
return (double)sum / 2;
...
```
იმიტომ რომ .....

ასევე სწორი ამოხსნა იქნება

```java
...
return (firstNumber + secondNumber) / 2.0;
...
```
იმიტომ რომ ...

2022-10-13 14:49 UTC, iomodo requested changes
მგონი ბოლო შენიშვნებია :)

2022-10-13 14:49 UTC, iomodo commented on problem-set/Average.md
> +1. თითOეული რიცხვის შეტანისას უნდა გამოვიყენოთ **readInt()** მეთოდი, რომელსაც არგუმენტად კონსოლში დასაბეჭდი ტექსი გადაეცემა, რისი დაბეჭდვის შემდეგაც ის დაუცდის მომხმარებელის შეყვანილ რიცხვს. მაგალითა
```suggestion
1. თითოეული რიცხვის შეტანისას უნდა გამოვიყენოთ **readInt()** მეთოდი, რომელსაც არგუმენტად კონსოლში დასაბეჭდი ტექსი გადაეცემა, რისი დაბეჭდვის შემდეგაც ის დაუცდის მომხმარებელის შეყვანილ რიცხვს. მაგალითად, ჩვენ შეგვიძლია გამოვიყენოთ **readInt("Enter the first number: ");** და **readInt("Enter the second number: ");** პირველი და მეორე რიცხვების შესაყვანად. შესაბამისად, კონსოლში დაიწერება **Enter the first number:** და კონსოლი დაუცდის მომხმარებლის შეყვანილ რიცხვს. რიცხვის შეყვანის შემდეგ კონსოლში დაიწერება **Enter the second number:** და კონსოლი ისევ დაუცდის მომხმარების შეყვანილ რიცხვს.
```

2022-10-13 14:49 UTC, iomodo commented on problem-set/Average.md
> +ასევე სწორი ამოხსნა იქნებოდა, თუ დავწერდით **return (firstNumber + secondNumber) / 2.0;**, რადგან ამ შემთხვევაში **2.0**_ის დაწერით **2** გადავკასტეთ **double** _ში, ამიტომ საბოლოო პასუხიც **double**
```suggestion
ასევე სწორი ამოხსნა იქნებოდა, თუ დავწერდით **return (firstNumber + secondNumber) / 2.0;**, რადგან ამ შემთხვევაში **2.0**-ის დაწერით გაყოფის ოპერატორი მუშაობს როგორც მანდვილ რიცხვებზე გაყოფა, ამიტომ საბოლოო პასუხიც **double** იქნება და არა **int**. მაგალითად,როცა პირველი რიცხვი არის **5**, მეორე კი **8**, მივიღებთ **(5 + 8) / 2.0 = 13 / 2.0 = 6.5**, რაც სწორი პასუხია.
```

2022-10-14 09:52 UTC, iomodo approved these changes
LGTM

2022-10-14 09:52 UTC, merged