Add implementation and solution to NumberOfDivisors issue
oseducation/programming-methodology-java pull request #62
Opened 2022-10-03 16:44 UTC by nika013

2022-10-13 17:47 UTC, iomodo requested changes
მშვენიერია, მცირე შენიშვნები სტილზე. მარკდაუნში ბევრი ენტერები და ტაბები გიწერია, რომლებსაც არანაირი დატვირთვა არ აქვთ. ჯობია წავშალოთ

2022-10-13 17:47 UTC, iomodo commented on problem-set/NumberOfDivisors.MD
> +    	}
```suggestion
    if (sqrtN * sqrtN == num) {
        cnt--;
    }
```

2022-10-13 17:47 UTC, iomodo commented on problem-set/NumberOfDivisors.java
> +import javax.swing.*;
ყველა import არ არის საჭირო

2022-10-13 17:47 UTC, iomodo commented on problem-set/NumberOfDivisors.java
> +import acm.program.*;
ფაილის თავში კომენტარი აკლია

2022-10-13 17:47 UTC, iomodo commented on problem-set/NumberOfDivisors.java
> +}
ენტერი ფაილის ბოლოში

2022-10-14 08:31 UTC, nika013 commented
ცვლილებები შევიტანე

2022-10-15 13:57 UTC, iomodo approved these changes
მშვენიერ!

2022-10-15 13:57 UTC, merged