Implemented Envrionment Setup Instruction For Linux Platform
oseducation/programming-methodology-java pull request #68
Opened 2022-10-13 08:54 UTC by Toms343

Linux Environment Setup

2022-10-13 18:19 UTC, iomodo requested changes
მშვენიერია, მცირე სტილისტიკური შენიშვნებია
`*`-ებს იყენებ ხოლმე არასწორად

2022-10-13 18:19 UTC, iomodo commented on problem-set/LinuxEnvironmentSetup.md
> +4.Stanford-ის ბიბლიოთეკის დაიმპორტება
არ ჩანს ნორმალურად, მარკდაუნის ლისტი გამოვიყენოთ ჯობია

2022-10-13 18:19 UTC, iomodo commented on problem-set/LinuxEnvironmentSetup.md
> +*მას შემდეგ რაც ტერმინალი გაიხსნება, შეიყვანეთ შემდეგი კოდი 'sudo apt install default-jre', შემდეგ შეიყვანთ თქვენს პაროლს, როგორც წესი თქვენი შეყვანილი პაროლი ტერმინალში არ გამოჩნდება მიტომ ნუ შეგეში
`*` რა საჭიროა? თუ ახალი ხაზი გინდა ჯობია ორი ენტერით გავაკეთოთ

2022-10-13 18:19 UTC, iomodo commented on problem-set/LinuxEnvironmentSetup.md
> +*მას შემდეგ რაც ტერმინალი გაიხსნება, შეიყვანეთ შემდეგი კოდი 'sudo apt install default-jre', შემდეგ შეიყვანთ თქვენს პაროლს, როგორც წესი თქვენი შეყვანილი პაროლი ტერმინალში არ გამოჩნდება მიტომ ნუ შეგეში
```suggestion
*მას შემდეგ რაც ტერმინალი გაიხსნება, შეიყვანეთ შემდეგი კოდი `sudo apt install default-jre`, შემდეგ შეიყვანთ თქვენს პაროლს, როგორც წესი თქვენი შეყვანილი პაროლი ტერმინალში არ გამოჩნდება მიტომ ნუ შეგეშინდებათ, უბრალოდ Enter-ს დააჭირეთ და ინსტალაციაც დაიწყება, თუ ყველაფერი სწორად გააკეთეთ
```

2022-10-13 18:19 UTC, iomodo commented on problem-set/LinuxEnvironmentSetup.md
> +*მას შემდეგ რაც ტერმინალი გაიხსნება, შეიყვანეთ შემდეგი კოდი 'sudo apt install default-jre', შემდეგ შეიყვანთ თქვენს პაროლს, როგორც წესი თქვენი შეყვანილი პაროლი ტერმინალში არ გამოჩნდება მიტომ ნუ შეგეში
ესენი ჯობია გამოიყენო ყველგან

2022-10-13 21:17 UTC, Toms343 commented
changes done upon request

2022-10-18 08:04 UTC, iomodo approved these changes
მშვენიერ!

2022-10-18 08:05 UTC, merged